export const DEFAULT_WHEEL_OPTIONS = {
    COUPLE: [
        "Overpriced pottery class",
        "Cat café",
        "Dog café",
        "Sunset cinema club – outdoor movie night (remember to carry insect repellent)",
        "Get dizzy in an amusement park",
        "Candlelight concert (not horror, the romantic kind)",
        "Indoor rock climbing",
        "Photo walk",
        "Colour walk – choose a colour, take a walk and click pictures of everything you find in your colour",
        "Gym together",
        "Attend a concert",
        "Go to a restaurant with live music",
        "Trip to Vietnam",
        "Trip to Europe",
        "Goa trip",
        "Weekend trip",
        "Immersive show exhibition",
        "Bookstore date",
        "Shopping date",
        "Cooking class",
        "Attend a dance class",
        "Dress hot and go clubbing",
        "Italian restaurant",
        "Burmese restaurant",
        "Café hopping",
        "Learn crochet",
        "Picnic in a park",
        "Pickleball date",
        "Book a badminton court (and play)",
        "Get a couple’s massage",
        "Trampoline park outing",
        "Watch a rom-com",
        "Art café",
        "Go paragliding",
        "Go skydiving",
        "Scuba diving",
        "Attend a stand-up comedy",
        "Water park",
        "Swimming date",
        "Build a LEGO set",
        "Attend a theatre play",
        "Go bowling",
        "Go karting",
        "Put your detective hat on and visit mystery rooms",
        "Tote bag painting",
        "Try canvas painting",
        "Make clay models",
        "Visit a zoo",
        "Visit a wildlife sanctuary",
        "Visit a monument",
        "5k run (spin again if you’re lazy)",
        "Sufi music night",
        "Jamming session",
        "Board game night",
    ],

    OTHER: [
        "Overpriced pottery class",
        "Cat cafe",
        "Dog cafe",
        "Sunset cinema club - outdoor movie night (remember to carry insect repellent)",
        "Get dizzy in an amusement park",
        "Indoor rock climbing",
        "Photo walk",
        "Colour walk - choose a colour, take a walk and click pictures of everything you find in your colour",
        "Gym together",
        "Attend a concert",
        "Go to a restaurant with live music",
        "Trip to vietnam",
        "Trip to europe",
        "Goa trip",
        "Weekend trip",
        "Immersive show exhibition",
        "Attend a dance class",
        "Dress hot and go clubbing",
        "Italian restaurant",
        "Burmese restaurant",
        "Cafe hopping",
        "Learn crochet",
        "Picnic in a park",
        "Book a badminton court (and play)",
        "Trampoline park outing",
        "Art cafe",
        "Go paragliding",
        "Go skydiving",
        "Scuba diving",
        "Attend a stand-up comedy",
        "Water park",
        "Build a lego set",
        "Attend a Theatre Play",
        "Go bowling",
        "Go karting",
        "Put your detective hat on and visit mystery rooms",
        "Tote bag painting",
        "Try canvas painting",
        "Make clay models",
        "Visit a zoo",
        "Visit a wildlife sanctuary",
        "Visit a monument",
        "5k run (spin again if you're lazy)",
        "Sufi music night",
        "Jamming session",
        "Board game night",
    ],
}